### NumPy - Numerical Python 

1. Python library for efficient numerical computations.
2. Supports large, multidimensional arrays and matrices.
3. Offers extensive mathematical functions library.

#### Advantages of Numpy Arrays :
1. Allows several Mathematical Operations
2. Faster operations

In [2]:
import numpy as np 

#### List VS Numpy - Time Taken

In [3]:
from time import process_time

Time taken by a list

In [4]:
a_list = [i for i in range(1000000)]
start_time = process_time()
a_list = [i+5 for i in a_list]
end_time = process_time()
print(end_time - start_time)

0.0625


In [5]:
np_array = np.array([i for i in range(1000000)])
start_time = process_time()
np_array += 5 
end_time = process_time()
print(end_time - start_time)

0.0


#### Numpy Arrays

In [6]:
a = [1,2,3,4,5]
print(a)
type(a)

[1, 2, 3, 4, 5]


list

In [7]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [8]:
# creating a 1 dim array 
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [9]:
a.shape  #  it will giive the number of rows and columns in the array

(4,)

In [10]:
# creating 2d array 
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
b.shape

(2, 4)

In [12]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype = float) # Changing the type of array
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


##### Placeholder in numpy array

In [13]:
# create a numpy array of Zeros
x = np.zeros((4,5)) # np.zeros is used for creating null values array
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
# crate a nuupy array for all values as one 
y = np.ones((5,5)) # np.ones is used for creating the all values as one 
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
# create a array of particular values 
z = np.full((5,4),5) # np.full is used for creating the array of particular values ((dimensions),values )
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [16]:
# create an identity matrix 
a = np.eye(5)  # np.eye is used for creating the identity matrix 
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
# create a numpy array with random values 
b = np.random.random((3,4)) # np.random.random is used and values between 0 and 1
print(b)

[[0.7070173  0.20415151 0.08085998 0.73699123]
 [0.50402881 0.25036438 0.7026153  0.11909693]
 [0.48813136 0.33600719 0.38224303 0.37883951]]


In [18]:
# random integer values array withing a specfic range 
c = np.random.randint(10,100,(3,5)) # np.random.randint ( , to specify the range the (value of the dimension)
print(c)

[[10 17 25 69 48]
 [51 18 96 55 81]
 [22 55 94 10 67]]


In [19]:
# array of evenly  spaced values like 
a = np.linspace(10,30,20) # with the gap of some range last (,,30) number of values you wants 
print(a)

[10.         11.05263158 12.10526316 13.15789474 14.21052632 15.26315789
 16.31578947 17.36842105 18.42105263 19.47368421 20.52631579 21.57894737
 22.63157895 23.68421053 24.73684211 25.78947368 26.84210526 27.89473684
 28.94736842 30.        ]


In [20]:
# array evenly spaced values like steps 
e = np.arange(10,30,5) # it will take the step of 5
print(e)

[10 15 20 25]


In [21]:
# convert a list into numpy array 
list = [5,4,9,7,8,5,42,1]
print(type(list))
np_array = np.asarray(list)
print(np_array)
type(np_array)

<class 'list'>
[ 5  4  9  7  8  5 42  1]


numpy.ndarray

In [22]:
# convert a tuple into numpy array 
tuple = (5,4,9,7,8,5,42,1)
print(type(tuple))
np_array = np.asarray(tuple)
print(np_array)
type(np_array)

<class 'tuple'>
[ 5  4  9  7  8  5 42  1]


numpy.ndarray

#### Analysing a numpy array 
Giving information about array

In [23]:
c = np.random.randint(10,90,(5,6))
print(c)

[[84 75 18 55 56 69]
 [28 45 56 21 14 84]
 [61 29 88 73 75 12]
 [25 59 48 21 32 32]
 [74 10 31 49 37 43]]


In [24]:
# array dimensions 
print(c.shape)  # it is about number of row and columns about arrays 

(5, 6)


In [25]:
# number of dimensions 
print(c.ndim) 


2


In [26]:
# checking number of elements present in the array 
print(c.size)


30


In [27]:
# checking the type of values present in the array
print(c.dtype)

int32


#### Mathematical Operations on numpy array

In [28]:
a = [1,2,3,4,5,6]
b = [5,6,7,8,9,1] 
print(a+b)  # it is not adding it is merging this two lists or concat the list 

[1, 2, 3, 4, 5, 6, 5, 6, 7, 8, 9, 1]


In [31]:
num1 = np.array([1,2,3,4,5,6])
num2 = np.array([5,6,7,8,9,10])
print(num1+num2) # it will add the array


[ 6  8 10 12 14 16]


In [32]:
a = np.random.randint(1,10,(5,5))
print(a)
b = np.random.randint(1,10,(5,5))
print(b)
print(a+b)  
print(a-b)
print(a*b)
print(a/b)

[[4 1 9 3 3]
 [4 3 3 6 8]
 [1 2 6 4 4]
 [2 2 1 3 8]
 [7 8 8 3 5]]
[[6 4 5 8 6]
 [1 5 2 7 1]
 [8 4 1 2 4]
 [4 5 5 4 4]
 [7 7 4 6 9]]
[[10  5 14 11  9]
 [ 5  8  5 13  9]
 [ 9  6  7  6  8]
 [ 6  7  6  7 12]
 [14 15 12  9 14]]
[[-2 -3  4 -5 -3]
 [ 3 -2  1 -1  7]
 [-7 -2  5  2  0]
 [-2 -3 -4 -1  4]
 [ 0  1  4 -3 -4]]
[[24  4 45 24 18]
 [ 4 15  6 42  8]
 [ 8  8  6  8 16]
 [ 8 10  5 12 32]
 [49 56 32 18 45]]
[[0.66666667 0.25       1.8        0.375      0.5       ]
 [4.         0.6        1.5        0.85714286 8.        ]
 [0.125      0.5        6.         2.         1.        ]
 [0.5        0.4        0.2        0.75       2.        ]
 [1.         1.14285714 2.         0.5        0.55555556]]


In [34]:
# other way of doing arithmetic operations 
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[10  5 14 11  9]
 [ 5  8  5 13  9]
 [ 9  6  7  6  8]
 [ 6  7  6  7 12]
 [14 15 12  9 14]]
[[-2 -3  4 -5 -3]
 [ 3 -2  1 -1  7]
 [-7 -2  5  2  0]
 [-2 -3 -4 -1  4]
 [ 0  1  4 -3 -4]]
[[24  4 45 24 18]
 [ 4 15  6 42  8]
 [ 8  8  6  8 16]
 [ 8 10  5 12 32]
 [49 56 32 18 45]]
[[0.66666667 0.25       1.8        0.375      0.5       ]
 [4.         0.6        1.5        0.85714286 8.        ]
 [0.125      0.5        6.         2.         1.        ]
 [0.5        0.4        0.2        0.75       2.        ]
 [1.         1.14285714 2.         0.5        0.55555556]]


#### Array Manipulation

In [35]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 1 1]
 [2 9 3]]
(2, 3)


In [38]:
# transpose 
trans = np.transpose(array) # it will convert row into column and vice versa
print(trans)
print(trans.shape)

[[4 2]
 [1 9]
 [1 3]]
(3, 2)


In [39]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 6 0]
 [7 1 7]]
(2, 3)


In [41]:
# other way of doing transpose 
trans2 = array.T  
print(trans2)
print(trans2.shape)

[[4 7]
 [6 1]
 [0 7]]
(3, 2)


In [43]:
# Reshape the array 
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[6 3 9]
 [5 3 0]]
(2, 3)


In [44]:
b = a.reshape(3,2)
print(b)
print(b.shape)


[[6 3]
 [9 5]
 [3 0]]
(3, 2)
